### ISSUE TITLE
[Feature Request] Add OnSpawn(taskname) Event

### ISSUE THREAD

**Issue by rikutons** [jedrzejboczar/toggletasks.nvim#14]
I want to make notification with any notification tool (like [this](https://github.com/rcarriga/nvim-notify[rcarriga/nvim-notify)) if one task gets evoked propely.
Can you add an event function when task spawned on setup config (and maybe when finished too)?

**Comment by jedrzejboczar** [comment]
You can use [toggleterm's callbacks](https://github.com/akinsho/toggleterm.nvim/blob/b02a1674bd0010d7982b056fd3df4f717ff8a57a/lua/toggleterm/terminal.lua#L62-L64), e.g.
```
require('toggletasks').setup {
    toggleterm = {
        on_create = function(term) vim.notify('Task terminal on_create') end,
        on_open = function(term) vim.notify('Task terminal on_open') end,
        on_close = function(term) vim.notify('Task terminal on_close') end,
        on_exit = function(term) vim.notify('Task terminal on_exit') end,
    },
}
```
And you can use the `Terminal` object that is passed to these functions to get back the `Task` object because toggletasks' terminals [are marked](https://github.com/jedrzejboczar/toggletasks.nvim/blob/f9c6f819ef44a78a8ad61855ec2913f992f9b989/lua/toggletasks/task.lua#L292) with `_task_id`. So you should be able to access the task object using `Task.get(term._task_id)` in the callback.

However, I just found that `on_create` doesn't work, which is a bug in toggleterm, I created a fix here: https://github.com/akinsho/toggleterm.nvim/pull/378, so this should work when the PR is merged.

**Comment by rikutons** [comment]
```
on_open = function(term)
  vim.notify("Task " .. Task.get(term._task_id).config.name .. " spawned")
end,
```
It works for me temporarily (I will change it after your PL marged).
I missed tooggleterm event existance, really thanks for best suggestion and quick fix!

**Comment by jedrzejboczar** [comment]
@rikutons Closing this as https://github.com/akinsho/toggleterm.nvim/pull/378 got merged.
