### ISSUE TITLE
Close task only if the process is successful 

### ISSUE THREAD

**Issue by isaksamsten** [jedrzejboczar/toggletasks.nvim#15]
Hi!

Great plug-in!

In my workflow I setup build tasks and want to run them hidden.

Would it be possible to have terms closed on exit, but only if the process ends successfully?

**Comment by jedrzejboczar** [comment]
This should do the job:
```lua
require('toggletasks').setup {
    toggleterm = {
        on_exit = function(term, job, exit_code, name)
            local Task = require('toggletasks.task')
            local task = Task.get(term._task_id)
            if not task then return end
            if exit_code == 0 then
                task:shutdown()
            else
                vim.notify('Task failed: ' .. task.config.name, vim.log.levels.ERROR)
            end
        end,
    },
}
```

**Comment by isaksamsten** [comment]
Thanks!

I can modify your code to only apply to certain tags!

**Comment by jedrzejboczar** [comment]
Glad that it works. Looking at your solution it's a nice idea to do this based on tag. But I think you might have an error in your code - the `else` branch will fire if the task has any tag that is not `"exit_on_success"`, so you could e.g. get the `vim.notify` message 3 times for a task with tags `{'tag1', 'tag2', 'tag3'}` when `exit_code != 0` because for each of them it would go to the `else` branch.

**Comment by isaksamsten** [comment]
Thanks for catching that :-)

in my config I have a break on match
