### ISSUE TITLE
How to get the value of environment variable in cmd?

### ISSUE THREAD

**Issue by JavaHello** [jedrzejboczar/toggletasks.nvim#4]
# Configure environment variables
```sh
export MY_CFG="xxxxxx"
```

# .tasks.json
```json
{
  "tasks": [
    {
      "name": "test",
      "cmd": "echo ${MY_CFG}"
    }
  ]
}

```

## error
```log
WARN Unknown expansion variable "MY_CFG"
```

**Comment by jedrzejboczar** [comment]
Environmental variables are deliberately not auto-expanded in `cmd` as noted in readme:

> Environmental variables will be expanded in fields: cwd, env. Additionally some special variables will be expanded in fields: cmd, cwd, env. 

This is because the shell itself can expand the variables. You can just use the following shell syntax `echo $MY_CFG`. It will be passed to your shell as-is and, because the shell will inherit environment from Neovim, it will expand the variable. If you want to use the syntax with braces you can escape it with `echo $${MY_CFG}`, which will pass `echo ${MY_CFG}` to your shell.

**Comment by JavaHello** [comment]
Thanks, `echo $MY_CFG` `echo $${MY_CFG}` works
