### ISSUE TITLE
How to properly close the task result window?

### ISSUE THREAD

**Issue by desilinguist** [jedrzejboczar/toggletasks.nvim#5]
Thanks for making a great plugin! I am finding it super useful!

One annoying thing I have found is that when I run a task, the output is shown at the bottom (in a split?) and if I just do `:q` to quit the split, the task is still considered "running" somehow because if I run `spawn` again, the list is empty? 

I have found that if I press `I` (insert mode) and then `x` in the task output window, it's somehow properly closed and then running spawn again shows the tasks. 

What am I doing wrong?

**Comment by jedrzejboczar** [comment]
> output is shown at the bottom (in a split?)

You can also use different orientation (e.g. floating window) by modifying [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim#multiple-orientations=) configuration.

> if I just do `:q` to quit the split, the task is still considered "running"

Yes, you are closing task window, but the buffer remains hidden. This way one can run tasks in the background. 

A task command X is spawned in its terminal buffer and this buffer is shown in some window. When X finishes, the then you will get a message like `[Process exited 0]`. Using `:q` you will just close the window, leaving the buffer untouched (you can re-open it via `Telescope toggletasks select`). To actually close the buffer you have to send any input in insert mode, so that's why `Ix` worked (I usually do `a<cr>`). 

This behaviour is generally quite useful, because you can inspect what was the output of the task. You could use `toggletasks.setup { defaults = { close_on_exit = true } }` to make the buffers close immediately (or manually pass `close_on_exit=true` in task constructor), but it will be impossible to see the output of short-running tasks like `echo 'hello world'`.

Also note that, when you closed a task window with `:q`, you can use `Telescope toggletasks select` combined with the `<C-q>` `<M-q>` mappings to kill the tasks without even opening their windows (mappings can be configured in the `setup()` function by `telescope.select.mappings.kill_*`).

**Comment by desilinguist** [comment]
This is extremely useful! Now it all makes sense. Thank you so much!
