### ISSUE TITLE
Feature Request: Passing Our Own Terminal Setup

### ISSUE THREAD

**Issue by cenk1cenk2** [jedrzejboczar/toggletasks.nvim#8]
Hey @jedrzejboczar ,

Thanks to this plugin, it saves me a lot of time doing repetitive tasks, and thank you for maintaining it!

But I have some issues with it, where I would like to ask whether it would be possible to pass our own terminal definition as default.

I have configured toggleterm to switch the terminals with keybindings just like the old floaterm to have the flexibility to have many terminals open simultaneously. But to achieve that I have to pass some trickery to on_open, on_exit operations.

This would also fix the issue for me (possibly) where, if a task has exited I can not focus that toggleterm window or toggle it out of the view.

**Comment by jedrzejboczar** [comment]
Hi, if I understand your situation correctly you should be able to pass on_open and on_exit in toggleterm setup like so:
```lua
require('toggleterm').setup {
    on_open = my_on_open,
    on_exit = my_on_exit,
}
```
These values are [used as defaults](https://github.com/akinsho/toggleterm.nvim/blob/2a787c426ef00cb3488c11b14f5dcf892bbd0bda/lua/toggleterm/terminal.lua#L189-L190) for all terminals in toggleterm, so toggletasks will also use these options (only [these options](https://github.com/jedrzejboczar/toggletasks.nvim/blob/f9c6f819ef44a78a8ad61855ec2913f992f9b989/lua/toggletasks/task.lua#L279-L287) get overridden). Unless you want to have different defaults for toggletasks, then we could make it possible to configure defaults for toggletasks.nvim separately. 

> This would also fix the issue for me (possibly) where, if a task has exited I can not focus that toggleterm window or toggle it out of the view.

Could you describe the issue in more detail? It is probably due to the fact that toggleterm deletes a buffer when the command exits when `close_on_exit=true`.

**Comment by cenk1cenk2** [comment]
Hello @jedrzejboczar ,

Thank you for the reply and your time. I suppose I have left out too many details to make this viable to understand.

It goes something like this for me where I do not use the default `on_open` and `on_close` handles.
- I have more than one set of terminals like ones for LazyGit, LazyDocker, etc that do not get counted in this switching by keybindings.
- I can have a separate bottom terminal which is also excluded.
- I can have a CWD terminal where it changes to the CWD of the current terminal.
- The ones that I use for switching with the keybindings are stored inside a Lua table where they can be switched on wherever the index is.
This behavior is defined [here](https://github.com/cenk1cenk2/nvim/blob/rolling/lua/extensions/toggleterm-nvim.lua).

So it can be a good solution in just my own specific case, where I can pass a function to create the terminal with specific settings so I can do keybinding switching on them. I suppose just propagating some options would be enough for me but passing a created terminal directly is even better.

The second thing that I am mentioning is I can not toggle the terminal out of the view if it has been already exited. It can only be closed for me. I am not sure if there is already a solution to keep them in the background because I sometimes need to go back and look at the line numbers of errors etc.

My settings for your beautiful plugin can be seen [here](https://github.com/cenk1cenk2/nvim/blob/rolling/lua/extensions/toggletasks-nvim.lua).

I do not know if the video of it would help, but I am attaching it anyway.

So it goes something like this, if I am not missing something on the toggle term side of things:
- If the application is still running, it is no problem to toggle the task runner.
- If the application has already exitted, the handle for `terminal:close()` does not work anymore. This causes me to go in insert mode in the task runner where it disposes of the terminal completely with the logs from the task runner.

The function I am using to close all toggleterm windows is [here](https://github.com/cenk1cenk2/nvim/blob/905539957fee62167cd4c54ecfb73f69ab45b8db/lua/extensions/toggleterm-nvim.lua#L364).

[recording_20220925-161229.webm](https://user-images.githubusercontent.com/26881592/192148184-c3609bb1-672a-4f67-9ffb-35bc2ddcabbb.webm)

**Comment by jedrzejboczar** [comment]
Thanks for the detailed description, interesting setup, though a bit complex :D 
But some thoughts from what I understood:

Regarding the second issue, that `terminal:close()` doesn't when a task has finished - I did some debugging and it looks like this is actually an issue with toggleterm itself. This is because when a task exits, `TermOpen` is fired, which [deletes this terminal from the list](https://github.com/akinsho/toggleterm.nvim/blob/2a787c426ef00cb3488c11b14f5dcf892bbd0bda/lua/toggleterm/terminal.lua#L140-L144), so your [get_all_terminals](https://github.com/cenk1cenk2/nvim/blob/905539957fee62167cd4c54ecfb73f69ab45b8db/lua/extensions/toggleterm-nvim.lua#L342) function doesn't return this terminal. You could try finding the terminals manually by iterating over existing buffers, or maybe it would be possible to extract `task.term` using [Task.get_all](https://github.com/jedrzejboczar/toggletasks.nvim/blob/f9c6f819ef44a78a8ad61855ec2913f992f9b989/lua/toggletasks/task.lua#L239) because toggletasks list is not emptied on `TermOpen` (but you have to check if buffer is still valid). 

Regarding the first problem, I am still not sure if I understand this 100%, so correct me if I am wrong - what you need is a way to do some specific things (set up keybindings, etc.) in on_open/on_close of the terminals, and also you need to do this differently in terminals spawned by toggletasks and differently in some other terminals? 
If so, then in theory you should be able to detect if this is a toggletasks terminal in your shared `on_open` by checking if this terminal is one of `Task.get_all()` (compare `task.term.bufnr` with `term` passed to `on_open`). But I can understand that it's a problematic solution, so I think that it would be better if I add an option to pass more defaults for terminals in `toggletasks.setup { defaults = ... }` (basically all terminal opts other than [cmd, dir and env](https://github.com/jedrzejboczar/toggletasks.nvim/blob/f9c6f819ef44a78a8ad61855ec2913f992f9b989/lua/toggletasks/task.lua#L279-L287)). If this would work for you then I can add it soon when I find some more time.

**Comment by cenk1cenk2** [comment]
Yes exactly, I think I have propagated my thought process through even though as you said it is an overly unnessarily complicated setup.

Since as you said toggleterm deletes the terminals from the list whenever they are exited, my solution is to keep them in a separate list as in [here](https://github.com/cenk1cenk2/nvim/blob/905539957fee62167cd4c54ecfb73f69ab45b8db/lua/extensions/toggleterm-nvim.lua#L239). I was just thinking that if I have the handle to pass it through this list, my keybindings for swapping terminals and toggling should work since it is kind of independent of toggleterm.

So exposing the parameters would be fine enough for me. But the only thing I wonder is how can I get the terminal class back whenever it is created by toggletasks to add to this list.

I can give this setup a try by opening up a draft of a merge request if you are also willing to add this as an option to your plugin.

**Comment by jedrzejboczar** [comment]
Ok, I'll try to add this to config tommorow. Feel free to open any draft PRs, it's always easier to discuss things when there is some code.

> how can I get the terminal class back whenever it is created by toggletasks to add to this list

Tasks [mark their terminal with an id](https://github.com/jedrzejboczar/toggletasks.nvim/blob/f9c6f819ef44a78a8ad61855ec2913f992f9b989/lua/toggletasks/task.lua#L292), so you should be able to retrieve it from the terminal object [which is passed as parameter](https://github.com/akinsho/toggleterm.nvim/blob/2a787c426ef00cb3488c11b14f5dcf892bbd0bda/lua/toggleterm/terminal.lua#L62) (note that the code later calls it as a method `self:on_open()`) in your shared `on_open(term)`. If the id is there then the terminal was created by toggletasks. You could then use `Task.get(id)` if you need the task object.

**Comment by jedrzejboczar** [comment]
@cenk1cenk2 could you check if https://github.com/jedrzejboczar/toggletasks.nvim/pull/9 works for you?

**Comment by cenk1cenk2** [comment]
Hey @jedrzejboczar,

Thank you very much for your time on this. Even though my case is very niche, I suppose everybody else can really use having the defaults for the toggleterm.

And even though I had done some workarounds, I did also manage to get my expected behavior working thanks to this update.

After a brick of text, I suppose this can visualize and summarize it as below:
[recording_20220926-221712.webm](https://user-images.githubusercontent.com/26881592/192372160-293a3228-adc3-4ffa-9aca-5012974a2a28.webm)

Sincerly thank you very much, I can close this issue with this being merge. Have a very nice day.
